apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Exposé publiquement
      targetPort: 80  # Correspond au conteneur Nginx
      nodePort: 30000  # Accessible depuis l'extérieur
  type: NodePort
