name: Go CI

on: [pull_request] # Run on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Go to the backend directory
        run: cd backend
      - name: Install dependencies
        run: cd backend && go mod tidy
      - name: Run tests
        run: cd backend && GO_ENV=test go test ./...
